### ISSUE TITLE
Informes de contadores de telegestión tipo 5

### ISSUE THREAD

**Issue by misern** [gisce/libCNMC#116]
S'ha de fer un informe trimestral sobre els comptadors tipus 5, telegestionsts, no telegestionats etc segons les indicacions del link adjunt de la CNMC.
(poseu la issue on toqui)
http://sede.cnmc.es/procedimiento.aspx?codigo=019

**Comment by ecarreras** [comment]
Això és el que va fer en @sim6 https://github.com/gisce/erp/pull/2366
