### ISSUE TITLE
Missing tariff mapping 

### ISSUE THREAD

**Issue by totaler** [gisce/libCNMC#268]
On [Utils Line 11](https://github.com/gisce/libCNMC/blob/master/libcnmc/utils.py#L11) lacks 6.X tariffs. 6.1A, 6.1B and 6.2 at least

**Comment by Xevib** [comment]
Fixed fo 6.1A and 6.2A on https://github.com/gisce/libCNMC/pull/305
I dont found the 6.1B and 6.2B code on https://www.boe.es/boe/dias/2015/07/31/pdfs/BOE-A-2015-8624.pdf

**Comment by Xevib** [comment]
The rest added on https://github.com/gisce/libCNMC/pull/306
