### ISSUE TITLE
Error amb multiprocess i conexió remota.

### ISSUE THREAD

**Issue by AdriNicolau** [gisce/libCNMC#322]
He estat realitzant unes modificacions a la llibreria i al testejar-la amb un servidor remot, m'he trobat que al llegir algun model p.e. 
```python
for tram in O.GiscedataAtTram.read(ids, fields_to_read):
```
retorna una llista d'enters en comptes d'una llista de diccionaris, de tal manera que **tram** en alguns casos era un enter i no un diccionari cosa que feia que al tractar-lo com un diccionari, llençava una exception. Amb en @Xevib hem arribat a la conclusió que podria ser una tema de concurrencia del multiprocess al realitzar la conexio amb XML-RPC, peró necesitaria una revisió més a fons.

**Comment by ecarreras** [comment]
Segurament és per això que dius, prova d'executar-ho com si fos natiu de la següent forma:

```sh
export PYTHONPATH=~/src/erp/server/bin:~/src/erp/server/bin/addons
export OPENERP_SERVER=/home/erp/conf/server.conf
```

A partir d'ara quan executis l'script de la `cnmc` ja ho farà amb ooop natiu.
